version: "2"

volumes:
  haproxy_cfg:
    driver: local

services:

  app:
    build: dockerfiles/app

  haproxy:
    image: haproxy:1.6
    ports:
      - "80:80"
    depends_on:
      - haproxy-gen
    volumes:
      - haproxy_cfg:/usr/local/etc/haproxy/
    restart: "always"

  haproxy-gen:
    build: dockerfiles/dockergen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - haproxy_cfg:/usr/local/etc/haproxy/
    environment:
      - "BACKEND=app"
      - "BACKEND_PORT=5000"
      - "SERVICE=haproxy"
      - "PROJECT=autohaproxy"